# 腾讯云 CNB (Cloud Native Builder) 构建配置文件
# L-Souljourney 博客 - 代码同步到GitHub方案

# 主分支 - 同步到GitHub触发GitHub Actions
main:
  push:
    - name: sync-to-github
      image: alpine/git
      # 从密钥仓库导入GitHub Token
      imports: https://cnb.cool/l-souljourney/env/-/blob/main/env.yml
      env:
        TZ: Asia/Shanghai
      
      script: |
        echo "🔄 开始同步代码到GitHub..."
        
        # 检查GitHub Token
        if [ -z "$GITHUB_TOKEN" ]; then
          echo "⚠️  未配置GITHUB_TOKEN，跳过同步"
          echo "💡 请在CNB密钥仓库中配置GITHUB_TOKEN环境变量"
          exit 0
        fi
        
        # 配置Git用户信息
        git config --global user.email "cnb-sync@l-souljourney.cn"
        git config --global user.name "CNB Auto Sync"
        
        # 添加GitHub远程仓库
        echo "📡 配置GitHub远程仓库..."
        git remote add github https://${GITHUB_TOKEN}@github.com/l-souljourney/souljourney-astro.git 2>/dev/null || true
        git remote set-url github https://${GITHUB_TOKEN}@github.com/l-souljourney/souljourney-astro.git
        
        # 推送到GitHub
        echo "📤 推送到GitHub仓库..."
        git push github main --force
        
        echo "✅ 代码同步完成！"
        echo "🚀 GitHub Actions将自动触发构建部署"
        echo "📊 同步信息:"
        echo "   - Git 提交: $CNB_GIT_COMMIT_SHA"
        echo "   - 分支: $CNB_GIT_REF"
        echo "   - 同步时间: $(date)"

# 开发分支 - 仅用于开发测试，不自动同步到GitHub
# 只有合并到main分支时才会触发GitHub同步和自动部署
develop:
  push:
    - name: develop-build-check
      image: node:18
      script: |
        echo "🧪 开发分支推送检查..."
        echo "📝 当前分支: develop"
        echo "💡 此分支不会自动同步到GitHub"
        echo "🔄 只有合并到main分支时才会触发部署"
        echo "✅ 开发分支检查完成"

# Pull Request - 同步到GitHub触发PR检查
"**":
  pull_request:
    - name: sync-pr-to-github
      image: alpine/git
      script: |
        echo "🔍 PR事件 - 同步到GitHub..."
        echo "💡 GitHub Actions将处理PR构建检查" 