version: '1.0'
name: "Astro博客双线部署"
description: "构建部署到腾讯云COS，同步到GitHub触发Cloudflare Pages"

# 构建环境配置
build:
  environment:
    image: "node:18"
    
  env:
    - NODE_ENV=production
    - ASTRO_TELEMETRY_DISABLED=1
    
  cache:
    paths:
      - "node_modules"
      - ".pnpm-store"
      
  steps:
    - name: "🔧 环境准备"
      script: |
        echo "=== 环境信息 ==="
        node --version
        npm --version
        echo "开始安装pnpm..."
        npm install -g pnpm
        pnpm --version
        echo "环境准备完成 ✅"
        
    - name: "📦 安装依赖"
      script: |
        echo "=== 安装项目依赖 ==="
        pnpm config set registry https://registry.npmmirror.com
        pnpm install --frozen-lockfile --store-dir .pnpm-store
        echo "依赖安装完成 ✅"
        
    - name: "🏗️ 构建项目"
      script: |
        echo "=== 开始构建Astro项目 ==="
        pnpm build
        echo "=== 构建产物检查 ==="
        ls -la dist/
        echo "文件总数: $(find dist -type f | wc -l)"
        echo "构建目录大小: $(du -sh dist/)"
        echo "项目构建完成 ✅"
        
    - name: "🚀 部署到腾讯云COS"
      script: |
        echo "=== 开始部署到腾讯云COS ==="
        echo "COS部署完成 ✅"
        
    - name: "📤 同步到GitHub"
      script: |
        echo "=== 同步到GitHub仓库 ==="
        git config user.name "CNB Auto Deploy"
        git config user.email "deploy@cnb.cool"
        git push https://${GITHUB_TOKEN}@github.com/l-souljourney/souljourney-astro.git HEAD:main --force
        echo "GitHub同步完成 ✅"

# 部署配置
deploy:
  cos:
    bucket: "${COS_BUCKET}"
    region: "ap-guangzhou"
    local_path: "./dist"
    remote_path: "/"
    clean: true
    
  cdn:
    domains:
      - "blog.l-souljourney.cn"
    paths:
      - "/*"

# 触发条件
triggers:
  - type: "push"
    branches:
      - "main"
  - type: "manual"

# 通知配置
notifications:
  success:
    message: |
      🎉 博客部署成功！
      🌐 国内访问: https://blog.l-souljourney.cn
      🌍 海外访问: Cloudflare Pages (自动构建中)
      
  failure:
    message: |
      ❌ 博客部署失败
      🔍 请检查构建日志
