# 腾讯云 CNB 构建配置文件
# L-Souljourney 博客项目

main:
  push:
    - docker:
        image: node:18-alpine
      stages:
        - echo "🔧 === 环境准备 ==="
        - node --version
        - npm --version
        - echo "安装pnpm..."
        - npm install -g pnpm
        - pnpm --version
        - echo "环境准备完成 ✅"
        - echo "📦 === 安装项目依赖 ==="
        - pnpm config set registry https://registry.npmmirror.com
        - pnpm install --frozen-lockfile
        - echo "依赖安装完成 ✅"
        - echo "🏗️ === 构建Astro项目 ==="
        - pnpm build
        - echo "=== 构建产物检查 ==="
        - ls -la dist/
        - echo "文件总数：$(find dist -type f | wc -l)"
        - echo "构建完成 ✅"
      plugins:
        - name: cnbcool/tencent-cos
          with:
            secret_id: ${COS_SECRET_ID}
            secret_key: ${COS_SECRET_KEY}
            bucket: ${COS_BUCKET}
            region: ${COS_REGION}
            src: dist/
            dest: /
            delete: true
        - name: cnbcool/tencent-cdn
          if: ${CDN_DOMAIN}
          with:
            domain: ${CDN_DOMAIN}
            secret_id: ${COS_SECRET_ID}
            secret_key: ${COS_SECRET_KEY}
            type: directory
            path: /

develop:
  push:
    - docker:
        image: node:18-alpine
      stages:
        - echo "🔧 === 开发环境构建测试 ==="
        - node --version
        - npm install -g pnpm
        - pnpm config set registry https://registry.npmmirror.com
        - pnpm install --frozen-lockfile
        - pnpm build
        - echo "开发构建测试完成 ✅"

"**":
  pull_request:
    - docker:
        image: node:18-alpine
      stages:
        - echo "🔍 === PR构建检查 ==="
        - node --version
        - npm install -g pnpm
        - pnpm config set registry https://registry.npmmirror.com
        - pnpm install --frozen-lockfile
        - pnpm build
        - echo "PR构建检查完成 ✅"

"$":
  push:
    name: 默认分支构建
    env:
      TZ: Asia/Shanghai
    image: node:18-alpine
    script: |
      echo "🔧 === 基础构建测试 ==="
      node --version
      npm install -g pnpm
      pnpm config set registry https://registry.npmmirror.com
      pnpm install --frozen-lockfile
      pnpm build
      echo "基础构建完成 ✅"
