# 腾讯云 CNB 构建配置文件
# L-Souljourney 博客项目

main:
  push:
    name: 主分支部署流水线
    env:
      TZ: Asia/Shanghai
    image: node:18-alpine
    stages:
      - name: 环境准备
        script: |
          echo "🔧 === 环境准备 ==="
          node --version
          npm --version
          echo "安装pnpm..."
          npm install -g pnpm
          pnpm --version
          echo "环境准备完成 ✅"
          
      - name: 安装依赖
        script: |
          echo "📦 === 安装项目依赖 ==="
          pnpm config set registry https://registry.npmmirror.com
          pnpm install --frozen-lockfile
          echo "依赖安装完成 ✅"
          
      - name: 构建项目
        script: |
          echo "🏗️ === 构建Astro项目 ==="
          pnpm build
          echo "=== 构建产物检查 ==="
          ls -la dist/
          echo "文件总数: $(find dist -type f | wc -l)"
          echo "构建完成 ✅"
          
      - name: 部署到COS
        image: cnbcool/tencent-cos
        script: |
          echo "🚀 === 部署到腾讯云COS ==="
          plugin-deploy
          echo "COS部署完成 ✅"
          
      - name: 刷新CDN
        image: cnbcool/tencent-cdn
        script: |
          echo "🔄 === 刷新CDN缓存 ==="
          plugin-refresh
          echo "CDN刷新完成 ✅"
          
      - name: 同步GitHub
        script: |
          echo "📤 === 同步到GitHub ==="
          if [ -n "$GITHUB_TOKEN" ]; then
            apk add --no-cache git
            git config --global user.email "cnb@l-souljourney.cn"
            git config --global user.name "CNB Deploy"
            git remote add github https://${GITHUB_TOKEN}@github.com/l-souljourney/souljourney-astro.git 2>/dev/null || true
            git remote set-url github https://${GITHUB_TOKEN}@github.com/l-souljourney/souljourney-astro.git
            git push github main --force
            echo "GitHub同步完成 ✅"
          else
            echo "⚠️ 未配置GITHUB_TOKEN，跳过同步"
          fi

develop:
  push:
    name: 开发分支测试流水线
    env:
      TZ: Asia/Shanghai
    image: node:18-alpine
    stages:
      - name: 构建测试
        script: |
          echo "🧪 === 开发分支构建测试 ==="
          npm install -g pnpm
          pnpm config set registry https://registry.npmmirror.com
          pnpm install --frozen-lockfile
          pnpm build
          echo "✅ 构建测试通过"

'**':
  pull_request:
    name: PR构建检查
    env:
      TZ: Asia/Shanghai
    image: node:18-alpine
    stages:
      - name: PR检查
        script: |
          echo "🔍 === PR构建检查 ==="
          npm install -g pnpm
          pnpm config set registry https://registry.npmmirror.com
          pnpm install --frozen-lockfile
          pnpm build
          echo "✅ PR检查通过"
