# 腾讯云 CNB 构建配置文件
# L-Souljourney 博客项目

# 通用配置锚点
.common_config: &common_config
  imports: https://cnb.cool/l-souljourney/env/-/blob/main/env.yml
  docker:
    image: node:18-alpine
  # 配置数据卷缓存
  volumes:
    - /cnb/cache/node_modules:/workspace/node_modules
    - /cnb/cache/pnpm-store:/root/.local/share/pnpm/store
    - /cnb/cache/pnpm-cache:/cnb/cache/pnpm-cache

# 通用构建步骤
.build_steps: &build_steps
  - echo "🔧 === 环境准备 ==="
  - node --version
  - echo "📦 === 配置pnpm ==="
  - npm install -g pnpm@latest
  - pnpm --version
  # 配置pnpm镜像源和缓存
  - pnpm config set registry https://mirrors.cloud.tencent.com/npm/
  - pnpm config set store-dir /root/.local/share/pnpm/store
  - pnpm config set cache-dir /cnb/cache/pnpm-cache
  - pnpm config set prefer-offline true
  # 简化网络配置，有缓存后降低超时设置
  - pnpm config set network-timeout 120000
  - pnpm config set fetch-retries 3
  - echo "📦 === 安装依赖 ==="
  - pnpm install --frozen-lockfile --prefer-offline
  - echo "🏗️ === 构建项目 ==="
  - pnpm build

main:
  push:
    - <<: *common_config
      stages:
        - *build_steps
        - echo "✅ === 构建完成 ==="
      plugins:
        - name: cnbcool/tencent-cos
          with:
            secret_id: ${COS_SECRET_ID}
            secret_key: ${COS_SECRET_KEY}
            bucket: ${COS_BUCKET}
            region: ${COS_REGION}
            src: dist/
            dest: /
            delete: true
        - name: cnbcool/tencent-cdn
          if: ${CDN_DOMAIN}
          with:
            domain: ${CDN_DOMAIN}
            secret_id: ${COS_SECRET_ID}
            secret_key: ${COS_SECRET_KEY}
            type: directory
            path: /
        - name: github-sync
          if: ${GITHUB_TOKEN}
          stages:
            - echo "📤 === 同步到GitHub ==="
            - apk add --no-cache git
            - git config --global user.name "CNB Deploy Bot"
            - git config --global user.email "noreply@cnb.cool"
            - git remote add github https://${GITHUB_TOKEN}@github.com/l-souljourney/souljourney-astro.git || git remote set-url github https://${GITHUB_TOKEN}@github.com/l-souljourney/souljourney-astro.git
            - git push github main --force
            - echo "✅ GitHub同步完成"

develop:
  push:
    - <<: *common_config
      stages:
        - *build_steps
        - echo "✅ === 开发测试完成 ==="

"**":
  pull_request:
    - <<: *common_config
      stages:
        - *build_steps
        - echo "✅ === PR检查完成 ==="


