# 腾讯云 CNB 构建配置文件
# L-Souljourney 博客项目 - Docker缓存方案

# 全局配置
workspace: 
  auto_init: false

# 环境变量导入
env:
  imports:
    - https://cnb.cool/l-souljourney/env/-/blob/main/env.yml

# ===== 分支配置 =====

# 主分支：生产环境构建+部署
main:
  trigger:
    push:
      - main
  job:
    - name: build-and-deploy
      docker:
        # 第一步：构建依赖缓存镜像
        - name: build-cache
          dockerfile: cache.dockerfile
          tag: cache:latest
          cache:
            paths:
              - package.json
              - pnpm-lock.yaml
        
        # 第二步：使用缓存镜像构建项目
        - name: build-project
          image: cache:latest
          commands:
            - /usr/local/bin/setup-cache.sh
            - /usr/local/bin/build-astro.sh

# 开发分支：仅构建测试
develop:
  trigger:
    push:
      - develop
  job:
    - name: build-test
      docker:
        # 第一步：构建依赖缓存镜像
        - name: build-cache
          dockerfile: cache.dockerfile
          tag: cache:latest
          cache:
            paths:
              - package.json
              - pnpm-lock.yaml
        
        # 第二步：使用缓存镜像构建项目
        - name: build-project
          image: cache:latest
          commands:
            - /usr/local/bin/setup-cache.sh
            - /usr/local/bin/build-astro.sh

# PR分支：快速构建检查
pull_request:
  trigger:
    target_branch:
      - main
      - develop
  job:
    - name: quick-check
      docker:
        image: node:18-alpine
        commands:
          - npm install -g pnpm
          - pnpm install
          - pnpm run build


